version: "3"
services:
  vue-app:
    image: autotracks-vue-docker
    ports:
      - "8080:8080"
    networks:
      - autotracks-app
  node-api:
    image: autotracks-api-docker
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - autotracks-app
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017" # use development connection string 'mongodb://mongo:27017/autotracks-test'
    networks:
      - autotracks-app
    volumes:
      - mongo-data:/data/db
networks:
  autotracks-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
